modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="rubyext"
version="1.0.0"
displayName="RubyExtension"
displayURL="https://mcreator.net"
credits="Mod by Raven, coding help by Glitchy606, Textures by Mariood and 3EMj. Inspired by Alphaver."
authors="Raven"
description="A new adventure from the people behind Minecraft! Adventure deep into the Rubylands to build, fight, explore, and connect!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.rubyext]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration