modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="rubyext"
version="1.0.0"
displayName="RubyExtension"
displayURL="https://mcreator.net"
credits="Mod by Raven, coding help by Glitchy606, Jappa textures by Mariood."
authors="StellarXRaven17"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.rubyext]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration