modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="rubyext"
version="1.0.0"
displayName="Rubylands Expansion Pack"
displayURL="https://mcreator.net"
credits="D4rkXF0xx17, Glitchy606, JustAFluffyBoi, Marioood, 3emj."
authors="Raven"
description=" An official expansion to the #1 Minecraft-type software! Build, fight and explore a world of fantasy, and uncover the history of the land's ancients!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.rubyext]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration